services:
  db: # Nome do serviço banco de dados 
    image: mysql:8.0 # baixado do Docker Hub (versão 8.0)
    container_name: consultorio-mysql 
    environment: 
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: consultorio_db # nome do banco de dados que será criado
      MYSQL_USER: user_app 
      MYSQL_PASSWORD: app_password
    ports: # mapeamento de portas
      - "3306:3306" # porta padrão do MySQL
    volumes: # persistência de dados
      - mysql_data:/var/lib/mysql # mapeia um volume Docker para a pasta de dados do MySQL dentro do contêiner

volumes: # definição dos volumes usados 
  mysql_data: # volume 'mysql_data' que definimos acima